from __future__ import annotations

from functools import lru_cache

try:
    from netaddr import EUI
    from netaddr.core import NotRegisteredError
except ImportError:
    EUI = None
    NotRegisteredError = Exception

OUI_TABLE: dict[str, tuple[str, str]] = {
    # ── Espressif (ESP8266 / ESP32 — vast majority of DIY/cheap IoT) ──────
    "18:FE:34": ("Espressif", "iot"),
    "24:0A:C4": ("Espressif", "iot"),
    "24:6F:28": ("Espressif", "iot"),
    "2C:F4:32": ("Espressif", "iot"),
    "30:AE:A4": ("Espressif", "iot"),
    "3C:61:05": ("Espressif", "iot"),
    "3C:71:BF": ("Espressif", "iot"),
    "40:F5:20": ("Espressif", "iot"),
    "48:3F:DA": ("Espressif", "iot"),
    "4C:11:AE": ("Espressif", "iot"),
    "50:02:91": ("Espressif", "iot"),
    "54:43:B2": ("Espressif", "iot"),
    "58:BF:25": ("Espressif", "iot"),
    "5C:CF:7F": ("Espressif", "iot"),
    "60:01:94": ("Espressif", "iot"),
    "64:B7:08": ("Espressif", "iot"),
    "68:C6:3A": ("Espressif", "iot"),
    "70:03:9F": ("Espressif", "iot"),
    "78:21:84": ("Espressif", "iot"),
    "7C:9E:BD": ("Espressif", "iot"),
    "80:7D:3A": ("Espressif", "iot"),
    "84:0D:8E": ("Espressif", "iot"),
    "84:CC:A8": ("Espressif", "iot"),
    "84:F3:EB": ("Espressif", "iot"),
    "8C:AA:B5": ("Espressif", "iot"),
    "90:97:D5": ("Espressif", "iot"),
    "94:B5:55": ("Espressif", "iot"),
    "98:F4:AB": ("Espressif", "iot"),
    "A0:20:A6": ("Espressif", "iot"),
    "A4:7B:9D": ("Espressif", "iot"),
    "A4:CF:12": ("Espressif", "iot"),
    "AC:67:B2": ("Espressif", "iot"),
    "B4:E6:2D": ("Espressif", "iot"),
    "BC:DD:C2": ("Espressif", "iot"),
    "C4:4F:33": ("Espressif", "iot"),
    "C8:2B:96": ("Espressif", "iot"),
    "D8:A0:1D": ("Espressif", "iot"),
    "DC:4F:22": ("Espressif", "iot"),
    "E0:98:06": ("Espressif", "iot"),
    "E8:DB:84": ("Espressif", "iot"),
    "EC:FA:BC": ("Espressif", "iot"),
    "F0:08:D1": ("Espressif", "iot"),
    "F4:CF:A2": ("Espressif", "iot"),
    # ── Raspberry Pi ──────────────────────────────────────────────────────
    "B8:27:EB": ("Raspberry Pi", "iot"),
    "DC:A6:32": ("Raspberry Pi", "iot"),
    "E4:5F:01": ("Raspberry Pi", "iot"),
    # ── VMware ────────────────────────────────────────────────────────────
    "00:05:69": ("VMware", "vmware_esxi"),
    "00:0C:29": ("VMware", "vmware_esxi"),
    "00:1C:14": ("VMware", "vmware_esxi"),
    "00:50:56": ("VMware", "vmware_esxi"),
    # ── Cisco ─────────────────────────────────────────────────────────────
    "00:00:0C": ("Cisco", "network_device"),
    "00:1A:A1": ("Cisco", "network_device"),
    "00:1B:54": ("Cisco", "network_device"),
    "00:1C:57": ("Cisco", "network_device"),
    "58:AC:78": ("Cisco", "network_device"),
    "68:86:A7": ("Cisco", "network_device"),
    "A0:EC:F9": ("Cisco Meraki", "network_device"),
    "88:F0:31": ("Cisco", "network_device"),
    "CC:D8:C1": ("Cisco", "network_device"),
    # ── Juniper ───────────────────────────────────────────────────────────
    "00:10:DB": ("Juniper", "network_device"),
    "00:12:1E": ("Juniper", "network_device"),
    "2C:6B:F5": ("Juniper", "network_device"),
    "28:8A:1C": ("Juniper", "network_device"),
    # ── MikroTik ──────────────────────────────────────────────────────────
    "00:0C:42": ("MikroTik", "network_device"),
    "18:FD:74": ("MikroTik", "network_device"),
    "2C:C8:1B": ("MikroTik", "network_device"),
    "48:8F:5A": ("MikroTik", "network_device"),
    "4C:5E:0C": ("MikroTik", "network_device"),
    "6C:3B:6B": ("MikroTik", "network_device"),
    "74:4D:28": ("MikroTik", "network_device"),
    "B8:69:F4": ("MikroTik", "network_device"),
    "CC:2D:E0": ("MikroTik", "network_device"),
    "D4:CA:6D": ("MikroTik", "network_device"),
    "E4:8D:8C": ("MikroTik", "network_device"),
    # ── TP-Link ───────────────────────────────────────────────────────────
    "18:D6:C7": ("TP-Link", "wifi_ap"),
    "50:C7:BF": ("TP-Link", "wifi_ap"),
    "64:70:02": ("TP-Link", "wifi_ap"),
    "98:DA:C4": ("TP-Link", "wifi_ap"),
    "AC:84:C6": ("TP-Link", "wifi_ap"),
    "B4:B0:24": ("TP-Link", "wifi_ap"),
    "EC:08:6B": ("TP-Link", "wifi_ap"),
    "F8:1A:67": ("TP-Link", "wifi_ap"),
    "54:AF:97": ("TP-Link", "wifi_ap"),
    "C4:E9:84": ("TP-Link", "wifi_ap"),
    "50:D4:F7": ("TP-Link", "wifi_ap"),
    "30:DE:4B": ("TP-Link", "wifi_ap"),
    # ── Netgear ───────────────────────────────────────────────────────────
    "00:09:5B": ("Netgear", "wifi_ap"),
    "00:14:6C": ("Netgear", "wifi_ap"),
    "00:1B:2F": ("Netgear", "wifi_ap"),
    "00:1E:2A": ("Netgear", "wifi_ap"),
    "00:22:3F": ("Netgear", "wifi_ap"),
    "20:E5:2A": ("Netgear", "wifi_ap"),
    "28:C6:8E": ("Netgear", "wifi_ap"),
    "44:94:FC": ("Netgear", "wifi_ap"),
    "84:1B:5E": ("Netgear", "wifi_ap"),
    "A0:04:60": ("Netgear", "wifi_ap"),
    "C0:3F:0E": ("Netgear", "wifi_ap"),
    "2C:30:33": ("Netgear", "wifi_ap"),
    # ── ASUS ──────────────────────────────────────────────────────────────
    "00:0C:6E": ("ASUS", "wifi_ap"),
    "00:11:2F": ("ASUS", "wifi_ap"),
    "00:1A:92": ("ASUS", "wifi_ap"),
    "04:D4:C4": ("ASUS", "wifi_ap"),
    "08:60:6E": ("ASUS", "wifi_ap"),
    "10:BF:48": ("ASUS", "wifi_ap"),
    "14:DD:A9": ("ASUS", "wifi_ap"),
    "2C:FD:A1": ("ASUS", "wifi_ap"),
    "30:5A:3A": ("ASUS", "wifi_ap"),
    "38:2C:4A": ("ASUS", "wifi_ap"),
    "50:46:5D": ("ASUS", "wifi_ap"),
    "54:04:A6": ("ASUS", "wifi_ap"),
    "74:D0:2B": ("ASUS", "wifi_ap"),
    "88:D7:F6": ("ASUS", "wifi_ap"),
    "AC:22:0B": ("ASUS", "wifi_ap"),
    "BC:AE:C5": ("ASUS", "wifi_ap"),
    "F8:32:E4": ("ASUS", "wifi_ap"),
    "90:E6:BA": ("ASUS", "wifi_ap"),
    # ── Ubiquiti ──────────────────────────────────────────────────────────
    "00:15:6D": ("Ubiquiti", "wifi_ap"),
    "00:27:22": ("Ubiquiti", "wifi_ap"),
    "04:18:D6": ("Ubiquiti", "wifi_ap"),
    "0C:80:63": ("Ubiquiti", "wifi_ap"),
    "18:E8:29": ("Ubiquiti", "wifi_ap"),
    "24:A4:3C": ("Ubiquiti", "wifi_ap"),
    "44:D9:E7": ("Ubiquiti", "wifi_ap"),
    "68:72:51": ("Ubiquiti", "wifi_ap"),
    "74:83:C2": ("Ubiquiti", "wifi_ap"),
    "78:8A:20": ("Ubiquiti", "wifi_ap"),
    "80:2A:A8": ("Ubiquiti", "wifi_ap"),
    "B4:FB:E4": ("Ubiquiti", "wifi_ap"),
    "DC:9F:DB": ("Ubiquiti", "wifi_ap"),
    "E0:63:DA": ("Ubiquiti", "wifi_ap"),
    "F0:9F:C2": ("Ubiquiti", "wifi_ap"),
    "FC:EC:DA": ("Ubiquiti", "wifi_ap"),
    # ── D-Link ────────────────────────────────────────────────────────────
    "00:05:5D": ("D-Link", "wifi_ap"),
    "00:0D:88": ("D-Link", "wifi_ap"),
    "00:11:95": ("D-Link", "wifi_ap"),
    "00:15:E9": ("D-Link", "wifi_ap"),
    "00:17:9A": ("D-Link", "wifi_ap"),
    "00:19:5B": ("D-Link", "wifi_ap"),
    "00:1B:11": ("D-Link", "wifi_ap"),
    "00:1C:F0": ("D-Link", "wifi_ap"),
    "00:1E:58": ("D-Link", "wifi_ap"),
    "1C:7E:E5": ("D-Link", "wifi_ap"),
    "28:10:7B": ("D-Link", "wifi_ap"),
    "5C:D9:98": ("D-Link", "wifi_ap"),
    "84:C9:B2": ("D-Link", "wifi_ap"),
    "C8:BE:19": ("D-Link", "wifi_ap"),
    # ── Apple (macOS / iOS — disambiguated by open ports in classify) ──────
    "00:03:93": ("Apple", "macos"),
    "00:0A:27": ("Apple", "macos"),
    "00:0A:95": ("Apple", "macos"),
    "00:11:24": ("Apple", "macos"),
    "00:14:51": ("Apple", "macos"),
    "00:16:CB": ("Apple", "macos"),
    "00:17:F2": ("Apple", "macos"),
    "00:19:E3": ("Apple", "macos"),
    "00:1B:63": ("Apple", "macos"),
    "00:1C:B3": ("Apple", "macos"),
    "00:1D:4F": ("Apple", "macos"),
    "00:1E:52": ("Apple", "macos"),
    "00:1F:5B": ("Apple", "macos"),
    "00:1F:F3": ("Apple", "macos"),
    "00:21:E9": ("Apple", "macos"),
    "00:22:41": ("Apple", "macos"),
    "00:23:12": ("Apple", "macos"),
    "00:25:00": ("Apple", "macos"),
    "00:25:BC": ("Apple", "macos"),
    "00:26:BB": ("Apple", "macos"),
    "04:26:65": ("Apple", "mobile"),
    "04:4B:ED": ("Apple", "mobile"),
    "04:D3:CF": ("Apple", "mobile"),
    "08:70:45": ("Apple", "mobile"),
    "0C:3E:9F": ("Apple", "mobile"),
    "0C:74:C2": ("Apple", "mobile"),
    "0C:BC:9F": ("Apple", "mobile"),
    "10:40:F3": ("Apple", "mobile"),
    "18:AF:61": ("Apple", "mobile"),
    "1C:91:48": ("Apple", "mobile"),
    "20:76:93": ("Apple", "mobile"),
    "28:37:37": ("Apple", "mobile"),
    "34:12:98": ("Apple", "mobile"),
    "34:C0:59": ("Apple", "mobile"),
    "38:66:F0": ("Apple", "mobile"),
    "3C:15:C2": ("Apple", "mobile"),
    "40:30:04": ("Apple", "mobile"),
    "40:D3:2D": ("Apple", "mobile"),
    "4C:57:CA": ("Apple", "mobile"),
    "58:55:CA": ("Apple", "mobile"),
    "5C:96:9D": ("Apple", "mobile"),
    "60:F8:1D": ("Apple", "mobile"),
    "6C:40:08": ("Apple", "mobile"),
    "70:EC:E4": ("Apple", "mobile"),
    "78:4F:43": ("Apple", "mobile"),
    "7C:FA:DF": ("Apple", "mobile"),
    "80:BE:05": ("Apple", "mobile"),
    "84:B1:53": ("Apple", "mobile"),
    "8C:7C:92": ("Apple", "mobile"),
    "90:72:40": ("Apple", "mobile"),
    "94:E9:6A": ("Apple", "mobile"),
    "98:01:A7": ("Apple", "mobile"),
    "9C:F3:87": ("Apple", "mobile"),
    "A4:B1:97": ("Apple", "mobile"),
    "A8:51:AB": ("Apple", "mobile"),
    "AC:BC:32": ("Apple", "mobile"),
    "B0:35:9F": ("Apple", "mobile"),
    "B4:F0:AB": ("Apple", "mobile"),
    "BC:9F:EF": ("Apple", "mobile"),
    "C0:63:94": ("Apple", "mobile"),
    "C8:2A:14": ("Apple", "mobile"),
    "CC:44:63": ("Apple", "mobile"),
    "D0:03:4B": ("Apple", "mobile"),
    "D4:DC:CD": ("Apple", "mobile"),
    "D8:96:95": ("Apple", "mobile"),
    "DC:2B:2A": ("Apple", "mobile"),
    "E0:B5:2D": ("Apple", "mobile"),
    "E4:CE:8F": ("Apple", "mobile"),
    "E8:04:0B": ("Apple", "mobile"),
    "EC:35:86": ("Apple", "mobile"),
    "F0:D1:A9": ("Apple", "mobile"),
    "F4:1B:A1": ("Apple", "mobile"),
    "F8:1E:DF": ("Apple", "mobile"),
    # ── Samsung ───────────────────────────────────────────────────────────
    "00:12:47": ("Samsung", "mobile"),
    "00:15:99": ("Samsung", "mobile"),
    "00:16:32": ("Samsung", "mobile"),
    "00:17:C9": ("Samsung", "mobile"),
    "00:1A:8A": ("Samsung", "mobile"),
    "00:1B:98": ("Samsung", "mobile"),
    "00:1C:43": ("Samsung", "mobile"),
    "00:1D:25": ("Samsung", "mobile"),
    "00:1E:7D": ("Samsung", "mobile"),
    "00:21:19": ("Samsung", "mobile"),
    "00:23:39": ("Samsung", "mobile"),
    "00:24:54": ("Samsung", "mobile"),
    "00:E3:B2": ("Samsung", "mobile"),
    "04:18:0F": ("Samsung", "mobile"),
    "04:1B:BA": ("Samsung", "mobile"),
    "08:D4:2B": ("Samsung", "mobile"),
    "0C:14:20": ("Samsung", "mobile"),
    "14:49:BC": ("Samsung", "mobile"),
    "20:13:E0": ("Samsung", "mobile"),
    "28:98:7B": ("Samsung", "mobile"),
    "34:31:C4": ("Samsung", "mobile"),
    "40:0E:85": ("Samsung", "mobile"),
    "48:44:F7": ("Samsung", "mobile"),
    "50:01:BB": ("Samsung", "mobile"),
    "54:88:0E": ("Samsung", "mobile"),
    "5C:49:79": ("Samsung", "mobile"),
    "60:A1:0A": ("Samsung", "mobile"),
    "68:27:37": ("Samsung", "mobile"),
    "6C:F3:73": ("Samsung", "mobile"),
    "78:40:E4": ("Samsung", "mobile"),
    "84:25:DB": ("Samsung", "mobile"),
    "8C:77:12": ("Samsung", "mobile"),
    "94:35:0A": ("Samsung", "mobile"),
    "98:52:B1": ("Samsung", "mobile"),
    "A8:06:00": ("Samsung", "mobile"),
    "B0:72:BF": ("Samsung", "mobile"),
    "C0:BD:D1": ("Samsung", "mobile"),
    "CC:07:AB": ("Samsung", "mobile"),
    "D0:22:BE": ("Samsung", "mobile"),
    "E4:92:FB": ("Samsung", "mobile"),
    "F4:42:8F": ("Samsung", "mobile"),
    # ── Xiaomi ────────────────────────────────────────────────────────────
    "00:9E:C8": ("Xiaomi", "mobile"),
    "04:CF:8C": ("Xiaomi", "iot"),
    "14:F6:5A": ("Xiaomi", "mobile"),
    "18:59:36": ("Xiaomi", "mobile"),
    "20:82:C0": ("Xiaomi", "mobile"),
    "28:6C:07": ("Xiaomi", "mobile"),
    "34:80:B3": ("Xiaomi", "iot"),
    "38:A4:ED": ("Xiaomi", "mobile"),
    "3C:BD:D8": ("Xiaomi", "mobile"),
    "50:64:2B": ("Xiaomi", "mobile"),
    "58:44:98": ("Xiaomi", "mobile"),
    "5C:E8:EB": ("Xiaomi", "mobile"),
    "64:09:80": ("Xiaomi", "mobile"),
    "64:B4:73": ("Xiaomi", "iot"),
    "68:DF:DD": ("Xiaomi", "mobile"),
    "78:02:F8": ("Xiaomi", "mobile"),
    "90:C7:92": ("Xiaomi", "iot"),
    "98:FA:E3": ("Xiaomi", "mobile"),
    "A0:86:C6": ("Xiaomi", "mobile"),
    "AC:C1:EE": ("Xiaomi", "mobile"),
    "CC:2D:83": ("Xiaomi", "iot"),
    "F0:B4:29": ("Xiaomi", "mobile"),
    # ── Google (Chromecast / Nest / Pixel) ────────────────────────────────
    "00:1A:11": ("Google", "iot"),
    "1C:F2:9A": ("Google", "iot"),
    "20:DF:B9": ("Google", "iot"),
    "48:D6:D5": ("Google", "iot"),
    "54:60:09": ("Google", "iot"),
    "58:6D:8F": ("Google", "iot"),
    "6C:AD:F8": ("Google", "iot"),
    "94:95:A0": ("Google", "iot"),
    "A4:77:33": ("Google", "iot"),
    "C8:FF:28": ("Google/Nest", "iot"),
    "E4:F0:42": ("Google", "iot"),
    "F4:F5:D8": ("Google", "iot"),
    # ── Amazon (Echo / Fire / Ring) ───────────────────────────────────────
    "00:BB:3A": ("Amazon", "iot"),
    "10:AE:60": ("Amazon", "iot"),
    "18:74:2E": ("Amazon", "iot"),
    "28:EF:01": ("Amazon", "iot"),
    "34:D2:70": ("Amazon", "iot"),
    "38:F7:3D": ("Amazon", "iot"),
    "40:B4:CD": ("Amazon", "iot"),
    "50:DC:E7": ("Amazon", "iot"),
    "68:37:E9": ("Amazon", "iot"),
    "74:C2:46": ("Amazon", "iot"),
    "84:D6:D0": ("Amazon", "iot"),
    "A0:02:DC": ("Amazon", "iot"),
    "AC:63:BE": ("Amazon", "iot"),
    "B4:7C:9C": ("Amazon", "iot"),
    "CC:9E:A2": ("Amazon", "iot"),
    "F0:27:2D": ("Amazon", "iot"),
    "F0:4F:7C": ("Amazon", "iot"),
    "FC:A1:83": ("Amazon", "iot"),
    "B0:09:DA": ("Ring/Amazon", "iot"),
    # ── Philips Hue ───────────────────────────────────────────────────────
    "00:17:88": ("Philips Hue", "iot"),
    "EC:B5:FA": ("Philips Hue", "iot"),
    # ── Sonos ─────────────────────────────────────────────────────────────
    "00:0E:58": ("Sonos", "iot"),
    "34:7E:5C": ("Sonos", "iot"),
    "48:A6:B8": ("Sonos", "iot"),
    "54:2A:1B": ("Sonos", "iot"),
    "78:28:CA": ("Sonos", "iot"),
    "94:9F:3E": ("Sonos", "iot"),
    "B8:E9:37": ("Sonos", "iot"),
    # ── Hikvision / Dahua (IP cameras) ───────────────────────────────────
    "44:19:B6": ("Hikvision", "iot"),
    "4C:BD:8F": ("Hikvision", "iot"),
    "54:C4:15": ("Hikvision", "iot"),
    "A0:AC:22": ("Hikvision", "iot"),
    "C0:56:E3": ("Hikvision", "iot"),
    "90:02:A9": ("Dahua", "iot"),
    "E4:24:6C": ("Dahua", "iot"),
    # ── HP (printers & ProCurve switches) ─────────────────────────────────
    "00:01:E6": ("HP", "printer"),
    "00:01:E7": ("HP", "printer"),
    "00:08:02": ("HP", "printer"),
    "00:11:0A": ("HP", "printer"),
    "00:12:79": ("HP", "printer"),
    "00:13:21": ("HP", "printer"),
    "00:14:38": ("HP", "printer"),
    "00:17:08": ("HP", "printer"),
    "00:18:71": ("HP", "printer"),
    "00:1A:4B": ("HP", "printer"),
    "00:1B:78": ("HP", "printer"),
    "00:1C:C4": ("HP", "printer"),
    "00:1E:0B": ("HP", "printer"),
    "00:1F:29": ("HP", "printer"),
    "00:21:5A": ("HP", "printer"),
    "00:22:64": ("HP", "printer"),
    "00:23:7D": ("HP", "printer"),
    "00:25:B3": ("HP", "printer"),
    "00:30:C1": ("HP", "printer"),
    "28:92:4A": ("HP", "printer"),
    # ── Epson ─────────────────────────────────────────────────────────────
    "00:04:AC": ("Epson", "printer"),
    "00:26:AB": ("Epson", "printer"),
    "44:D2:44": ("Epson", "printer"),
    "64:EB:8C": ("Epson", "printer"),
    "AC:18:26": ("Epson", "printer"),
    # ── Canon ─────────────────────────────────────────────────────────────
    "00:00:85": ("Canon", "printer"),
    "00:1E:8F": ("Canon", "printer"),
    "14:C2:13": ("Canon", "printer"),
    "68:26:F2": ("Canon", "printer"),
    # ── Brother ───────────────────────────────────────────────────────────
    "00:1B:A9": ("Brother", "printer"),
    "00:80:77": ("Brother", "printer"),
    "28:84:FA": ("Brother", "printer"),
    # ── Xerox ─────────────────────────────────────────────────────────────
    "00:00:AA": ("Xerox", "printer"),
    "00:00:51": ("Xerox", "printer"),
}


def normalize_mac(mac: str) -> str:
    return mac.upper().replace("-", ":")


def lookup_oui(mac: str) -> tuple[str | None, str | None]:
    curated_manufacturer, platform_hint = OUI_TABLE.get(mac[:8], (None, None))
    manufacturer = curated_manufacturer or _registry_vendor(mac[:8])
    return manufacturer, platform_hint


@lru_cache(maxsize=8192)
def _registry_vendor(oui: str) -> str | None:
    if EUI is None:
        return None
    try:
        return EUI(f"{oui}:00:00:00").oui.registration().org
    except (NotRegisteredError, Exception):
        return None


def is_randomized_mac(mac: str) -> bool:
    try:
        return bool(int(mac[:2], 16) & 0x02)
    except (ValueError, IndexError):
        return False
